---
- name: Firewall install and config
  hosts: all
  become: yes
  
  tasks:
  
  - name: install firewalld
    dnf:
      name: firewalld
      state: latest
      
  - name: start and enable firewalld
    service:
          name: firewalld
          state: started
          enabled: yes
          
  - name: create zone test1
    firewalld:
        zone: test1
        state: present
        permanent: true

  - name: add ports for RabbitMQ, REDIS, MariaDB and Zabbix agent to firewall
    firewalld:
        zone: test1
        port: "{{item}}"
        state: enabled
        permanent: true
    loop:
     - 4369/tcp           #RabbitMQ ports
     - 25672/tcp
     - 5671/tcp
     - 5672/tcp
     - 15672/tcp
     - 61613/tcp
     - 61614/tcp
     - 1883/tcp
     - 8883/tcp      
     - 6379/tcp           #Redis ports
     - 26379/tcp
     - 3306/tcp           #MariaDB ports
     - 4567/tcp
     - 4568/tcp
     - 4444/tcp            
     - 10050/tcp          #Zabbix port

  - name: add source of network
    firewalld:
        zone: test1
        source: 10.129.0.0/24
        state: enabled
        permanent: true
        
  - name: reload firewalld config
    systemd:
      name: firewalld
      state: reloaded