---
# tasks file for deploy-mariadb-cluster
- name: copy mariadb.repo file to nodes 
  copy: 
    src: mariadb.repo 
    dest: /etc/yum.repos.d/ 
    mode: 0644
 
- name: install mariadb-server and mariadb-client 
  yum: 
    name: MariaDB-server, MariaDB-client 
    state: latest
      
- name: copy MariaDB config file to nodes 
  template: 
    src: z-custom-my.j2 
    dest: /etc/my.cnf.d/z-custom-my.cnf
       
- name: start galera_new_cluster on node1 
  shell: galera_new_cluster 
  run_once: True
    
- name: start and enable mariadb service 
  service: 
    name: mariadb 
    state: started
    enabled: yes
